// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "go-boilerplate/domain"

	mock "github.com/stretchr/testify/mock"
)

// PlayerService is an autogenerated mock type for the PlayerService type
type PlayerService struct {
	mock.Mock
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *PlayerService) GetByID(ctx context.Context, id string) (*domain.Player, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Player
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Player, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Player); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Player)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPlayerService creates a new instance of PlayerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPlayerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PlayerService {
	mock := &PlayerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
